
--[[ PhysicsHelper
  Defines some useful physics functions not provided natively by Box2D.
--]]
local PhysicsHelper = {}


--[[ PhysicsHelper.getSpeed
  Returns the magnitude of an object's linear velocity.
  
  body: Body object.
--]]
function PhysicsHelper.getSpeed(body)
  
  local vx, vy = body:getLinearVelocity()
  return math.sqrt(vx^2 + vy^2)
  
end


--[[ PhysicsHelper.getMoveAngle
  Returns the angle of an object's direction of travel.
  
  body: Body object.
--]]
function PhysicsHelper.getMoveAngle(body)
  
  local vx, vy = body:getLinearVelocity()
  return math.atan2(vy, vx)
  
end


--[[ PhysicsHelper.getRelativeSpeed
  Returns the speed of an object relative to its own facing, in the forward and lateral directions.
  
  body: Body object.
--]]
function PhysicsHelper.getRelativeSpeed(body)
  
  local vx, vy = body:getLinearVelocity()
  local vAngle = math.atan2(vy, vx)
  local theta = (math.pi / 2) + body:getAngle() - vAngle
  
  local vForward = math.cos(vAngle - body:getAngle()) * math.sqrt(vx^2 + vy^2)
  local vLateral = math.cos(theta) * math.sqrt(vx^2 + vy^2)
  
  return vForward, vLateral
  
end


--[[ PhysicsHelper.getUnitFacingVector
  Returns the unit vector corrsponding to an objects's current direction of facing.
  
  body: Body object.
--]]
function PhysicsHelper.getUnitFacingVector(body)
  
  local ux = math.cos(body:getAngle())
  local uy = math.sin(body:getAngle())
  
  return ux, uy
  
end


--[[ PhysicsHelper.pacejka
  Returns the traction force generated by a tire using Pacekja Magic Formula.
  
  wheelLoad: Vertical load on the tire.
  slip: Slip ratio or sidesli angle.
  B, C, D, E: Coefficients.
--]]
function PhysicsHelper.pacejka(wheelLoad, slip, B, C, D, E)
  
  local Bslip = B * slip
  return wheelLoad * D * math.sin(C * math.atan(Bslip - E * (Bslip - math.atan(Bslip))))
  
end


return PhysicsHelper
